apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: nginx-deploy
  labels: 
    app: nginx-deploy  
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: nginx-deploy 
  template: 
    metadata:
      labels: 
        app: nginx-deploy 
    spec: 
      containers: 
        - name: nginx 
          image: nginx
          volumeMounts: 
            - name: nginx-html
              mountPath: /var/www/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes: 
        - name: nginx-html 
          persistentVolumeClaim:
            claimName: pvc-nginx
        - name: nginx-config
          configMap:
            name: nginx-configmap
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf:  |
    server {
        listen 1234;
        server_name localhost;
        root /var/www/html;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }
    }

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 192.168.56.11
    path: /home/vagrant/nfs

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
provisioner: nfs
parameters:
  server: 192.168.56.11
  path: /home/vagrant/nfs
reclaimPolicy: Retain
volumeBindingMode: Immediate
